### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by hkmztrk** [eharpste/molparser#1]
Hello,

`mols = parse_sdf_file(CMP_PATH+sdff,True,True,True,n=25000)`

I'm trying to parse a pubchem sdf file (Compound_000000001_000025000.sdf), but I'm getting the following error:

```
  File "convertmol.py", line 220, in apply_m_iso
    if k.startswith('?atom'):
AttributeError: 'tuple' object has no attribute 'startswith'
```

Could you please help me about this?

Thanks

**Comment by eharpste** [comment]
Looks like I wasn't accounting for the possibility of tuples already being in the object in a few places. I just pushed a fix that should take care of that. Let me know if you run into any other issues.
